### PR TITLE
add TapDeck as 3rd party example

### PR DESCRIPTION
**Pull request by AndreasZeiser**

### CODE REVIEW

**Comment by chrislacy** [comment]
My sincerest apologies for the delay merging this.

**Review by devilshezi0 — APPROVED** [review]

**Comment by devilshezi0** [comment]
>
3af968150646ec3a9215350a979c19a93423cd33

**Comment by AndreasZeiser** [comment]
Hey @devilshezi0 Thank you for merging this PR. Unfortunately our service TapDeck doesn't exist anymore. So please revert this PR. I'm sorry that I didn't deleted the PR before.

**Comment by devilshezi0** [comment]
Hello. Sir chrislacy, how are you? I hope you are fine. Thank you so much. No problem. I don't know much about this think I am free, like no work, soo playing with my mind and Mobile

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
